artifacts_root: D:/Python Project/TextSummarize-NLP/artifacts

data_ingestion:
  root_dir: D:/Python Project/TextSummarize-NLP/artifacts/data_ingestion
  source_URL: "https://github.com/quochuy242/Dataset/raw/master/summarizer-data.zip"
  local_data_file: D:/Python Project/TextSummarize-NLP/artifacts/data_ingestion/data.zip
  unzip_dir: D:/Python Project/TextSummarize-NLP/artifacts/data_ingestion

data_validation:
  root_dir: D:/Python Project/TextSummarize-NLP/artifacts/data_validation
  STATUS_FILE: D:/Python Project/TextSummarize-NLP/artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ['train', 'test', 'validation']

data_transformation:  
  root_dir: D:/Python Project/TextSummarize-NLP/artifacts/data_transformation
  data_path: D:\Python Project\TextSummarize-NLP\artifacts\data_ingestion\summarizer-data\samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail

model_trainer:
  root_dir: D:/Python Project/TextSummarize-NLP/artifacts/model_trainer
  data_path: D:\Python Project\TextSummarize-NLP\artifacts\data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail

model_evaluation:
  root_dir: D:/Python Project/TextSummarize-NLP/artifacts/model_evaluation
  data_path: D:\Python Project\TextSummarize-NLP\artifacts\data_transformation/samsum_dataset
  model_path: D:\Python Project\TextSummarize-NLP\artifacts\model_trainer\pegasus-samsum-model
  tokenizer_path: D:\Python Project\TextSummarize-NLP\artifacts\model_trainer\tokenizer
  metric_file_name: D:/Python Project/TextSummarize-NLP/artifacts/model_evaluation/metric.csv