artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/quochuy242/Dataset/blob/master/samsum-dataset.rar
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion